### ISSUE TITLE
Remove sample texts and placeholders

### ISSUE THREAD

**Issue by FahadLive** [rohankishore/rohankishore.github.io#1]
I just had a look at your site and I found out that there are some sample texts and placeholders left in Resume and portfolio pages

![image](https://github.com/user-attachments/assets/8b327d9d-ef89-4832-9a4d-3f3ebb665cff)

If you are still working on it, you can just disable it for now (if that's possible) :)

**Comment by rohankishore** [comment]
Yep. Got it. Thanks a lot for your suggestion ☺️
